development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: ebrahim.el.gaml@gmail.com
  :password: 0121838455
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: ebrahim.el.gaml@gmail.com
  :password: 0121838455
  :enable_starttls_auto: true